### ISSUE TITLE
File based settings

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1451]
**Is your feature request related to a problem? Please describe.**

Many settings are editable from the admin UI and are stored in the database.

I suggest to move most of these settings currently in the DB to a dedicated configuration file, or the one we already have. In my case, this allow easier backup/modifications between deployment, for settings that actually does not change that often. This should also simplify other aspects of the configuration handling.

I am mostly thinking about the following settings :
- Server timezone
- Week start day
- CORS
- Public API toggle
- Streams settings
  - Global stream settings
  - Output streams settings
  - Live streaming settings 

I we want to go all the way down this road, we might also consider moving some other settings to a file based storage, but we should leave it editable from the admin UI.

**Comment by paddatrapper** [comment]
This sounds reasonable to me

**Comment by zklosko** [comment]
The stream settings may change when troubleshooting, so they should still be accessible to admins.

**Comment by jooola** [comment]
The only issue we need to fix to move forward with this, is how to handle handle environment variables when running in a docker environment.

This might become tricky when handling stream settings. We could put a hard requirements on a file based configuration, but I would try to avoid this.

**Comment by zklosko** [comment]
I don't see the harm extra database reads would be doing. I guess they could be Redis variables if we were going to replace RabbitMQ, but I don't see the need.

**Comment by jooola** [comment]
## From cc_pref

| keystr                          | valstr                             |
| ------------------------------- | ---------------------------------- |
| timezone                        | Europe/Paris                       |
| allowed_cors_urls               | https://station.radio.org          |
| live_stream_master_password     | SOME_SECRET                        |
| live_stream_master_username     | source                             |
| live_dj                         | false                              |
| live_dj_source_connection_url   | http://stream.radio.org:8802/show  |
| master_dj                       | false                              |
| master_dj_source_connection_url | http://station.radio.org:8801/main |

## From cc_stream_setting

| keyname                  | value                 | type    |
| ------------------------ | --------------------- | ------- |
| icecast_vorbis_metadata  | true                  | boolean |
| dj_live_stream_mp        | /show                 | string  |
| dj_live_stream_port      | 8802                  | integer |
| master_live_stream_mp    | /main                 | string  |
| master_live_stream_port  | 8801                  | integer |
| output_sound_device      | false                 | boolean |
| output_sound_device_type | ALSA                  | string  |
| s\*\_admin_pass          | SOME_SECRET           | string  |
| s\*\_admin_user          | admin                 | string  |
| s\*\_bitrate             | 256                   | integer |
| s\*\_channels            | stereo                | string  |
| s\*\_description         | Main (ogg 256kbps)    | string  |
| s\*\_enable              | true                  | boolean |
| s\*\_genre               |                       | string  |
| s\*\_host                | stream.radio.org      | string  |
| s\*\_mobile              | 0                     |         |
| s\*\_mount               | main.ogg              | string  |
| s\*\_name                | Radio                 | string  |
| s\*\_output              | icecast               | string  |
| s\*\_pass                | SOME_SECRET           | string  |
| s\*\_port                | 8800                  | integer |
| s\*\_type                | ogg                   | string  |
| s\*\_url                 | https://www.radio.org | string  |
| s\*\_user                | source                | string  |

## To yaml

```yml
timezone: Europe/Paris
allowed_hosts:
  - https://station.radio.org
  - https://www.radio.org

live_streams:
  main:
    port: 8001
    mount_point: /main
    username: source
    password: SOME_SECRET
    public_url: https://live-stream.radio.org/main

  show:
    port: 8002
    mount_point: /show
    username: source
    password: SOME_SECRET
    public_url: https://live-stream.radio.org/show

icecast_outputs:
  - enabled: true
    # Meta
    name: Radio
    description: Main (ogg 256kbps)
    url: https://www.radio.org
    genre: various
    # Audio
    format: ogg
    bitrate: 256
    channels: stereo
    # Icecast
    host: localhost
    port: 8000
    mount_point: /main.ogg
    admin_username: admin
    admin_password: SOME_SECRET
    username: source
    password: SOME_SECRET
    public_url: https://stream.radio.org/main.ogg

  - enabled: true
    # Meta
    name: Radio
    description: Main (mp3 256kbps)
    url: https://www.radio.org
    genre: various
    # Audio
    format: mp3
    bitrate: 256
    channels: stereo
    # Icecast
    host: localhost
    port: 8000
    mount_point: /main.mp3
    admin_username: admin
    admin_password: SOME_SECRET
    username: source
    password: SOME_SECRET
    public_url: https://stream.radio.org/main.mp3
```

**Comment by paddatrapper** [comment]
Looks good. My only comment would be that some of the settings are optional (e.g. `public_url`) and I'm not sure how, but we should add validation on the number of icecast outputs supported. Much of the code base (especially liquidsoap) works on the assumption that there are 4 configured with 1 or more active.

**Comment by paddatrapper** [comment]
Not sure if we want to break it up more:

```yaml
icecast_outputs:
  - enabled: true
    metadata:
      name: LibreTime
      description: Stream description
      [...]
    audio:
        format: mp3
        bitrate: 256
        channels: 2
    icecast:
        host: localhost
        [...]

**Comment by jooola** [comment]
> Not sure if we want to break it up more:

This might help use reuse some component for additional future output, such as hls.

**Comment by paddatrapper** [comment]
Could even be

```yaml
outputs:
  - enabled: true
    [...]
    connection:
      type: Icecast
      host: localhost
      [...]
```
That way we can add support for other streaming providers (e.g. shoutcast) without requiring people to change their configuration files
