### ISSUE TITLE
Docker error 'no matching manifest for linux/arm64/v8 in the manifest list entries'

### ISSUE THREAD

**Issue by markst** [libretime/libretime#2435]
### Describe the bug

Attempting to setup database using Docker on m2 MacBook air, the api fails to pull due to no matching manifest for arm64.

### Relevant log output or error messages
```bash
mt@mt-mba libretime % docker-compose run --rm api libretime-api migrate

[+] Running 2/0
 ⠿ Container libretime-rabbitmq-1  Running                                                                                                                           0.0s
 ⠿ Container libretime-postgres-1  Running                                                                                                                           0.0s
[+] Running 0/1
 ⠋ api Pulling                                                                                                                                                       2.1s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### LibreTime version
3.0.2

### Installation method and OS / Environment
```
Software:
    System Software Overview:
      System Version: macOS 13.1 (22C65)
Hardware:
    Hardware Overview:
      Model Name: MacBook Air
      Model Identifier: Mac14,2
      Chip: Apple M2
```

**Comment by markst** [comment]
Is this potentially as simple as including `platform` in the api specs?:

```yaml
  api:
    platform: linux/arm64
    image: ghcr.io/libretime/libretime-api:${LIBRETIME_VERSION:-latest}
    depends_on:
      - postgres
      - rab...
 ```
